import "~/styles/globals.css";

import { Geist, Geist_Mono, Inter } from "next/font/google";

import { AppSidebar } from "./_components/app-sidebar";
import Providers from "./providers";
import { SidebarInset } from "./_components/ui/sidebar";
import { SiteHeader } from "./_components/site-header";
import { Toaster } from "./_components/ui/toaster";
import { cn } from "~/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>
      <body
        className={cn(
          "overscroll-none bg-background font-sans text-foreground antialiased",
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <Providers>
          <AppSidebar variant="inset" />
          <SidebarInset>
            <SiteHeader />
            <div className="flex flex-1 flex-col">
              <div className="@container/main container flex flex-1 flex-col gap-2 py-4">
                {children}
              </div>
            </div>
          </SidebarInset>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
